### ISSUE TITLE
Store full history of dat

### ISSUE THREAD

**Issue by joehand** [datproject/dat-store#10]
dat-librarian uses dat-node under the hood. Because it stores the files on disk, it doesn't support the full history. I assumed dat-store did store history but hadn't really thought through it.

We should store history =). Happy to discuss how to best do this. And TBH we should be clearer about this in dat-node, though I would like to store history by default if possible.

**Comment by plankatron** [comment]
-history off/on  with a statement informing you then?

**Comment by joehand** [comment]
I realized you can pass `latest: false` to dat-node and then it stores full history (but doesn't store files as files). That may be a good option for now. See a bit more in [dat-backup](https://github.com/joehand/dat-backup)

**Comment by RangerMauve** [comment]
This should be handled with this commit: https://github.com/datproject/dat-store/commit/eab23938f8ffe66f1c8d96c02e003b943905eb0e

By default we will store the entire history, and you can have it store just the latest history by passing `--latest` to `dat store run-service`
