### ISSUE TITLE
Document implications of running a storage provider

### ISSUE THREAD

**Issue by Frando** [datproject/dat-store#13]
When running a storage provider, an HTTP endpoint ist exposed that lists all stored dats. As the keys of the dats are included in this list, that means that by running a storage provider and adding dats to it, you basically make these dats public. That might not be what users intend to do (they might assume that by adding a dat to a storage provider, it would remain private as long as the key is not published in another way. Therefore, the current behaviour should be documented, and maybe even made optional (or possibly add some token based authentication or similar).

**Comment by RangerMauve** [comment]
That's a really good point! Would you be open to submitting a PR to add some thing to that extent to the README?

I was also thinking of pointing people more towards [homebase](https://github.com/beakerbrowser/homebase/) if they want a fancier provider that's on the internet.
