### ISSUE TITLE
install-service doesn't work on macos

### ISSUE THREAD

**Issue by beingalink** [datproject/dat-store#14]
The command `dat store install-service`results in:
```
/usr/local/lib/node_modules/dat-store/index.js:126
    if (e) throw e
           ^

Error: writeFile(/etc/init.d/dat-store) failed: ENOENT: no such file or directory, open '/etc/init.d/dat-store'
    at /usr/local/lib/node_modules/dat-store/node_modules/os-service/index.js:293:11
    at fs.open (fs.js:1190:7)
    at FSReqCallback.args [as oncomplete] (fs.js:145:20)
```
macOS 10.14.4
node v11.14.0

**Comment by karissa** [comment]
Right now I don't think dat-store is intended for use on macs, instead can you try running `dat-store run-service`?

**Comment by beingalink** [comment]
I made this issue by request of @RangerMauve on irc. He said he wanted to look for a module that supports macos, too. As launchd should be similar enough to systemd, I think this would make sense.

**Comment by karissa** [comment]
@beingalink thanks! so `run-service` works for you?

**Comment by beingalink** [comment]
Yes, `run-service`seems to work, at least there's no error message but a json line with server information. I didn't try running a real dat though.

**Comment by RangerMauve** [comment]
Gonna close this for now, a PR for README for manually setting up a service on mac would be nice.
