### ISSUE TITLE
Trouble with install-service on Ubuntu

### ISSUE THREAD

**Issue by canadaduane** [datproject/dat-store#15]
This is from chat logs, but wanted to post here so it doesn't get lost:

I couldn't run `dat store install-service` as my regular user (result was `EACCES: permission denied, open '/etc/init.d/dat-store'`), so I tried `sudo` but npm complained:

`sudo: dat: command not found.`

Finally, I had to symlink my version of node to /usr/local via
```sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/node" "/usr/local/bin/node"```
and
```sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/npm" "/usr/local/bin/npm"```

Then, I can login as root via `sudo bash` and `dat store install-service` seemed to succeed.

I also had a small issue with this error: `Error: EACCES: permission denied, open '/home/duane/.config/dat-store-nodejs/config.json.2768840111` but a `chown -R duane:duane /home/duane/.config/dat-store-nodejs` fixed it.

Currently, `dat-store` seems to be installed, but it is not "working" since it doesn't seem to be publishing the dats that I've added to the store (but `dat share` works ok).

**Comment by RangerMauve** [comment]
Just to confirm, which version of dat-store was this with?

**Comment by canadaduane** [comment]
It was the version just prior to your minor bump yesterday... 0.8? Sorry,
I'm just leaving for a trip so I can't check immediately.

**Comment by RangerMauve** [comment]
Thank you! No rush on checking. I think 2.0.9 should fix the issue of not being able to detect changes to files. There was a bug where the secret keys were being loaded for the archives.

**Comment by canadaduane** [comment]
Ok, thanks. I will give it a try tonight!

**Comment by DougAnderson444** [comment]
I ran `install-service` with `dat-store` 4.0.0 on ubuntu without any issue 👍
