### ISSUE TITLE
Possible reconnect issue on partially downloaded .dat

### ISSUE THREAD

**Issue by pepbrooks** [datproject/dat-store#17]
Hey Ranger, just installed dat-store and am running into a potential issue where if a reboot or some kind of interruption on initial download happens, there doesn't seem to be an attempt to reconnect to finish the download. Yet if another (new) .dat url the download will kick up on that one no issue. 

The full .dats I am attempting to download from are both stored on separate cli and homebase instances if that matters at all. So they should be served correctly on the local network.

Love the new tool to work with, and appreciate all the work put into it.

Edit: Even after a full download seems like the same issue

Edit:  ended up dats being served were on a different subnet. Served dats are on 10.0.10.x, dat-store instance on 192.168.0.x. Initial download works fantastic but cannot seem to reconnect. Removed the dat-store instance from the 192.168.0.x network and added to the 10.0.10.x network and the reconnect is working no problem.

Sorry about all the edits, I should have worked this out before I opened the issue.

**Comment by RangerMauve** [comment]
Weird, so this is more an issue of which network interfaces dat-store is sharing on? What do you think the correct behavior would be here?

**Comment by RangerMauve** [comment]
All the underlying stuff has been changed up, feel free to reopen the issue if it's still happening.
