### ISSUE TITLE
Request: Percentage of dat completed

### ISSUE THREAD

**Issue by pepbrooks** [datproject/dat-store#18]
One more and I'll get out of the way, any chance of adding an additional command to view the percentage completed of each dat, or possibly adding it as part of the dat-store list command?

**Comment by RangerMauve** [comment]
Would this command be used for something like viewing the "health" of a Dat archive within the store?

I'd like to limit the command list to things that work across different servers. Right now that means the stuff that's defined in [DEP 0003](https://www.datprotocol.com/deps/0003-http-pinning-service-api/) I think before we get health stuff into dat-store, we should get it into the DEP and into Hashbase.

**Comment by RangerMauve** [comment]
Oh, you could open an issue [here](https://github.com/datprotocol/DEPs/issues) to get the conversation started about standardizing getting the percentage from a server.

**Comment by pepbrooks** [comment]
Makes sense, I know I am not the first to have this bright idea. Thanks Ranger I'll keep an eye out down the road. Thanks again.
