### ISSUE TITLE
Support multiple providers

### ISSUE THREAD

**Issue by RangerMauve** [datproject/dat-store#2]
Based on feedback from @karissa, it would be useful if we could support having multiple (named) stores in the CLI.

It'd looks something like

```
dat store set-provider [name] <provider>

dat store add [name] <url>
```

Where `name` is the human readable name (kind of like a git branch), and `provider` is the URL of the provider. If the `name` isn't supplied, it should be set to `default` which will be set to `localhost` by default.

This is a big-ish change so I'd rather get some feedback on whether people want it before implementing.

**Comment by joehand** [comment]
We did this in the registry but can't quite remember how it worked. Did you take a look at that?

**Comment by RangerMauve** [comment]
Will do! I already have an idea on how this could work though. :P

**Comment by RangerMauve** [comment]
Working on this

**Comment by RangerMauve** [comment]
Added in https://github.com/datproject/dat-store/commit/bb249544e8f01f775a8e0127a49b2b408a1eeacc

It works by adding a `provider` option when doing an `add/remove/etc`

e.g.

```shell
# Configure external storage provider
dat-store set-provider hashbase https://hashbase.io/

dat-store login hashbase yourusername

dat-store add hashbase dat://0a9e202b8055721bd2bc93b3c9bbc03efdbda9cfee91f01a123fdeaadeba303e/
```
