### ISSUE TITLE
Is here any way to use a really dir to save content.data , so I can visit the data 

### ISSUE THREAD

**Issue by eyun-tv** [datproject/dat-store#20]
Is here any way to use a really dir to save content.data , so I can visit the data .

for now, I have to clone dat in another dir , so I can use the dat

**Comment by RangerMauve** [comment]
Yeah, I'm currently working on this feature in [this branch](https://github.com/datproject/dat-store/tree/sync-locally)

Basically, if you have a store running locally, you can use `dat clone dat://SomeURLHere` and `dat store add ./folder_that_you_cloned_to` and it'll work the same as running `dat sync` in the directory.

**Comment by RangerMauve** [comment]
This should be good to go now!
