### ISSUE TITLE
documentation for configuring service

### ISSUE THREAD

**Issue by missinglink** [datproject/dat-store#21]
heya,

I am following [the docs](https://docs.datproject.org/docs/dat-server#run-it-forever) to install an `os-service` (on OSX and Linux).

It's not immediately clear how I would go about configuring the service to use a non-standard directory for data storage.

The docs say that it uses [conf](https://github.com/sindresorhus/conf) and [env-paths](https://github.com/sindresorhus/env-paths#pathsdata) but it's not clear how I would go about creating a file to modify the default data directory (and where this file lives on disk).

**Comment by RangerMauve** [comment]
Check out the options section when you run `dat-store --help`

You can set the default data directory with the `  --storage-location` command.

Also check out [this part](https://github.com/datproject/dat-store#where-is-stuff-stored) of the readme. Installing the service as a daemon doesn't work on OSX at the moment, and it's still a bit buggy on linux. 😅 I'd advice using `dat store run-service` in the meantime and watching the repo for new releases.
