### ISSUE TITLE
Can’t upload from directories

### ISSUE THREAD

**Issue by da2x** [datproject/dat-store#25]
$ dat store run-service --port=3280 &
    $ mkdir test-directory/ && cd test-directory/
    $ touch file1 file2 file3
    $ dat create --yes=true --dir=./
    $ cat dat.json
    $ dat store add ./
    # then restart the dat-store service
    $ cd $(mktemp -d)
    $ dat clone dat://dat-key-ecoed-by-cat --port=3282

This never completes. No files are transferred.

Uploads seems to work fine when added via `dat store add dat://some-day-key` instead of adding a directory.

**Comment by RangerMauve** [comment]
Hey! I'm kinda swamped with other Dat stuff at the moment, but I've set a reminder to try to reproduce this on Monday around 15:00 EST

**Comment by RangerMauve** [comment]
This should be working now.
