### ISSUE TITLE
I broke dat-store list

### ISSUE THREAD

**Issue by DougAnderson444** [datproject/dat-store#35]
I was repeatedly hitting `dat-store list` about every 3 seconds, to see the list refresh, and then it just stopped working. Weird. I rebooted ubuntu, stopped and restarted the dat-store, all the cycling I could do, the psa doc still serves up, but no listing of the data anymore. 

It's strange, have no idea why, I'll see if I can figure it out but it's stumping me.

**Comment by DougAnderson444** [comment]
Ok, I will have a look at it and let you know!!

**Comment by DougAnderson444** [comment]
Ok, I've got a PR drafted, and I am trying to test this:
```
      manifest = Promise.race([
        await pda.readManifest(archive),
        new Promise((resolve, reject) => setTimeout(() => resolve(manifest), 500))
      ])
```
...once I get dat-store to run on my Windows 8 machine

**Comment by RangerMauve** [comment]
This should be fixed now
