### ISSUE TITLE
Question: --expose-to-internet also required for P2P functionality

### ISSUE THREAD

**Issue by jaller94** [datproject/dat-store#38]
Please clarify, if `--expose-to-internet` is also required for P2P sharing over the internet or only to allow remote configurations like `dat-store add <hash>` over the internet.

**Comment by RangerMauve** [comment]
Expose to internet is just for the HTTP server that dat-store uses for adding / removing archives. The P2P stuff uses the internet by default. Does that help disambiguate things a bit? 😁

**Comment by Powersource** [comment]
Yeah I misinterpreted this at first too and was almost about to expose my stuff to the internet which would have been bad. Maybe an update to the readme is needed.

**Comment by RangerMauve** [comment]
@Powersource Would you be down to take a shot at the README change? :P I'm not sure what the best wording would be.

**Comment by Powersource** [comment]
I think I would change the words "listen" and "expose" in this [paragraph](https://github.com/datproject/dat-store#how-do-i-expose-my-store-to-the-internet) to "control". And add a sentence something like "This flag is not needed to share/download archives over the internet, and is only intended for advanced users"
