### ISSUE TITLE
Support binding to specific interfaces

### ISSUE THREAD

**Issue by da2x** [datproject/dat-store#5]
It should be possible to specify which interfaces to listen on. Say I only want the service listening on `198.51.100.12` and `2001:db8::cafe` instead of every available interface on the system.

**Comment by RangerMauve** [comment]
I think it'd be useful to get all this configuration stuff standardized into a repo somewhere so we can reuse the logic.

**Comment by RangerMauve** [comment]
This is supported as part of the `--host` flag
