### ISSUE TITLE
Don't use home directory for storage

### ISSUE THREAD

**Issue by RangerMauve** [datproject/dat-store#8]
As per https://github.com/datproject/dat/issues/1093 we shouldn't be storing data in the `.dat` dir in the home folder. We should instead use the OS-specific folders for application data.

**Comment by RangerMauve** [comment]
I'm going to make use of the [conf](https://github.com/sindresorhus/conf) module for this.

**Comment by RangerMauve** [comment]
Added in https://github.com/datproject/dat-store/commit/a453c2988787d75c2552dd04bf4570e11ee3cc84

**Comment by 34r7h** [comment]
Similar problem.
`dat share`
Directory contains incompatible dat metadata. Please remove your old .dat folder (rm -rf .dat)
