### ISSUE TITLE
add folder support

### ISSUE THREAD

**Issue by plankatron** [datproject/dat-store#9]
trying to flesh out a feature for adding directories and not just keys to dat-store 

- ability to add directories with or without existing dat keys
- ability to have dat-store handle syncing all these local directories to the dat network thereby avoiding issues with multiple instances of dat running on a single computer 
- bonus points : sync level, full , partial or only latest changes ?

**Comment by RangerMauve** [comment]
Working on this now.

Here's what I'm thinking of for the workflow:

## If the store you're adding to is running remotely (isn't the default store)

- Resolve the full folder path
- Look up the key for the folder
- If it isn't a Dat, throw an error
- Send the key to the store the same way you normally would

## If the store you're adding to is running locally:
- Resolve the full folder path
- Look up the key for the folder
- If it isn't a Dat, throw an error
- Send the key, and the folder to the store
- The store checks that the request came from a local client if it has a folder path
- If the request isn't local, it'll just use the key
- If the request is local, it'll lookup the key from the folder, and add it and the folder to a separate list
- Folders in the list will be synced from the filesystem to the store regularly. Kind of like running dat share on the folder
- This will mean that you won't be able to run dat-share on that folder yourself while it's added

**Comment by RangerMauve** [comment]
The first part is ready in this commit: https://github.com/datproject/dat-store/commit/cf69dee94de31ec354b9c5f689872a0731b08079

Gonna work on the other half more tomorrow. :)

**Comment by RangerMauve** [comment]
Added the second case [here](https://github.com/datproject/dat-store/commit/123b79de85962596d0a158e2091a2f3e80a02ad8)

**Comment by RangerMauve** [comment]
This is out in 2.0.8 :)
